name: check-and-alert

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run checker
        env:
          FRAMADATE_URL:      ${{ secrets.FRAMADATE_URL }}
          PLAYER_NAME:        ${{ vars.PLAYER_NAME }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN:  ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_BASE_URL:  ${{ secrets.MAILGUN_BASE_URL }}
        run: python src/main.py --info
